### ISSUE TITLE
Contrato

### ISSUE THREAD

**Issue by JoseABCruz** [SistemasTecTlaxiaco/Festividad_3.0#75]

**Comment by JoseABCruz** [comment]
[Contrato de desarrollo.pdf](https://github.com/SistemasTecTlaxiaco/Festividad_3.0/files/13595426/Contrato.pdf)

**Comment by EdwinOrtiz1412** [comment]
50% felicidades 🍻🍻🍷

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
